#!/usr/bin/env Rscript
library(knitr)
knit('StructuralNetworks.Rnw',tangle=TRUE)
knit('StructuralNetworks.Rnw',tangle=FALSE)
for ( i in c(1,2,3) ) {
  system('pdflatex StructuralNetworks ')
  system('bibtex StructuralNetworks ')
}
system('rm *log *aux *blg *tex *out *bbl *spl')

